[build]
  command = "vite build" 
  base = "/consultoria"
  publish = "/dist"
  
  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
   
  from = "/api/*"
  to = "${env.API_URL}/:splat"
  status = 200
  force = true

[[headers]]
  
  for = "/*"
    [headers.values]
      Access-Control-Allow-Headers = "*"
      Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
      Access-Control-Allow-Credentials = "true"
